### PR TITLE
Add Stripe error message

### PR DESCRIPTION
**Pull request by jklockri**
https://trello.com/c/fAtJ2WJ4/128-handle-out-of-stock-error-when-a-user-tries-to-order-coffee-that-doesnt-exist-other-stripe-errors-in-order-completion-process

### CODE REVIEW

**Review by ghost — APPROVED** [review]

**Review by ghost — APPROVED** [review]
the real hound the real hound

**Comment by cdanmar** [comment]
Make sure that all spec is passing before attempting to submit, or else codeship will fail to build. If something is not passing, you can skip it by adding an "x" in front of it like so:

```
RSpec.describe "an example" do
  xit "is skipped using xit" do
  end

  xspecify "is skipped using xspecify" do
  end

  xexample "is skipped using xexample" do
  end
end
```

**Comment by misternu** [comment]
Closing stale PR

**Pull request closed without merging**
