### PR TITLE
Add modal to sign in on add item to cart click

### PR DESCRIPTION
**Pull request by ghost**

### CODE REVIEW

**Review by ghost — COMMENTED** [review]
+1000. That is some lovely code.

**Review by ghost — COMMENTED** [review]
+5000.

**Review by jklockri — APPROVED** [review]
+600 Good Jobbbb

**Comment by jklockri** [comment]
https://trello.com/c/78rdEWP0/62-as-an-anonymous-customer-i-will-be-asked-to-login-or-signup-before-checking-out

**Pull request merged**
