### PR TITLE
Customer dashboard change

### PR DESCRIPTION
**Pull request by dillonstreator**
Customer dashboard on one page displaying subscription info and account info

### CODE REVIEW

**Comment by heydanhey** [comment]
@DillonStreator Thanks for making this change! The only reason the build is failing is because the feature spec is looking for the string `Customer Dashboard` after a successful login.  Since you removed that text, we just need to update the spec with text that can confirm a successful login, like `Account Information` or anything unique to the customer show page. Can you update the file `/spec/features/customer_spec.rb`?

**Comment by dillonstreator** [comment]
The feature spec for customer sign in has been updated to look for 'Account Information' string now

**Comment by heydanhey** [comment]
@DillonStreator Thanks +1!

**Review by heydanhey — APPROVED** [review]
+1

**Pull request merged**
